// Auto-generated by scripts/gen-effects.mjs — do not edit by hand.
import type { ComponentType } from 'react';

export type EffectCategory = 'basic' | 'text' | 'interaction' | 'advanced';
export type ParamKind = 'range' | 'select';
export type EffectParam =
  | { kind: 'range'; key: string; label: string; min: number; max: number; step: number; default: number; unit?: string }
  | { kind: 'select'; key: string; label: string; options: string[]; default: string };
export interface EffectCode { html: string; css: string; js: string; }
export interface Effect {
  id: string; name: string; englishName: string;
  category: EffectCategory; tags: string[]; description: string;
  difficulty: 1 | 2 | 3; params: EffectParam[]; code: EffectCode;
  preview: () => Promise<{ default: ComponentType<{ params: Record<string, any> }> }>;
}

export const CATEGORIES: { id: EffectCategory | 'all'; name: string; english: string }[] = [
  { id: 'all', name: '全部', english: 'All' },
  { id: 'basic', name: '基础', english: 'Basic' },
  { id: 'text', name: '文字', english: 'Text' },
  { id: 'interaction', name: '交互', english: 'Interaction' },
  { id: 'advanced', name: '高级', english: 'Advanced' },
];

const lz = (id: string) => () => import(`@/components/effects/${id}`);

export const EFFECTS: Effect[] = [
  {
    id: 'fade-in',
    name: '淡入',
    englishName: 'Fade In',
    category: 'basic',
    tags: ['fade', 'basic'],
    description: '元素从透明渐入到不透明,最基础的进入动画。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.2, max: 3, step: 0.1, default: 0.8, unit: 's' },
      { kind: 'range', key: 'delay', label: '延迟', min: 0, max: 2, step: 0.1, default: 0, unit: 's' }
    ],
    code: {
      html: `<div class="fade-in">Hello</div>`,
      css: `.fade-in { animation: fadeIn var(--duration, 0.8s) ease-out var(--delay, 0s) both; }
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }`,
      js: `// Pure CSS — no JS needed`,
    },
    preview: lz('fade-in'),
  },
  {
    id: 'fade-in-up',
    name: '上滑淡入',
    englishName: 'Fade In Up',
    category: 'basic',
    tags: ['fade', 'basic'],
    description: '元素从下方淡入,常用于列表项。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.2, max: 3, step: 0.1, default: 0.8, unit: 's' },
      { kind: 'range', key: 'distance', label: '距离', min: 10, max: 80, step: 5, default: 20, unit: 'px' }
    ],
    code: {
      html: `<div class="fade-in-up">Hello</div>`,
      css: `.fade-in-up { animation: fadeInUp var(--duration, 0.8s) ease-out both; }
@keyframes fadeInUp { from { opacity: 0; transform: translateY(var(--distance, 20px)); } to { opacity: 1; transform: translateY(0); } }`,
      js: `// Pure CSS`,
    },
    preview: lz('fade-in-up'),
  },
  {
    id: 'slide-in-left',
    name: '左侧滑入',
    englishName: 'Slide In Left',
    category: 'basic',
    tags: ['slide', 'basic'],
    description: '元素从左侧滑入视口。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.2, max: 2, step: 0.1, default: 0.6, unit: 's' }
    ],
    code: {
      html: `<div class="slide-left">→</div>`,
      css: `.slide-left { animation: slideLeft var(--duration, 0.6s) ease-out both; }
@keyframes slideLeft { from { transform: translateX(-100%); } to { transform: translateX(0); } }`,
      js: ``,
    },
    preview: lz('slide-in-left'),
  },
  {
    id: 'slide-in-right',
    name: '右侧滑入',
    englishName: 'Slide In Right',
    category: 'basic',
    tags: ['slide', 'basic'],
    description: '元素从右侧滑入视口。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.2, max: 2, step: 0.1, default: 0.6, unit: 's' }
    ],
    code: {
      html: `<div class="slide-right">←</div>`,
      css: `.slide-right { animation: slideRight var(--duration, 0.6s) ease-out both; }
@keyframes slideRight { from { transform: translateX(100%); } to { transform: translateX(0); } }`,
      js: ``,
    },
    preview: lz('slide-in-right'),
  },
  {
    id: 'zoom-bounce',
    name: '缩放弹跳',
    englishName: 'Zoom Bounce',
    category: 'basic',
    tags: ['zoom', 'basic'],
    description: '元素放大入场,带弹跳回弹。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.3, max: 2, step: 0.1, default: 0.8, unit: 's' }
    ],
    code: {
      html: `<div class="zoom-bounce">●</div>`,
      css: `.zoom-bounce { animation: zoomBounce var(--duration, 0.8s) cubic-bezier(0.34, 1.56, 0.64, 1) both; }
@keyframes zoomBounce { from { transform: scale(0); } to { transform: scale(1); } }`,
      js: ``,
    },
    preview: lz('zoom-bounce'),
  },
  {
    id: 'flip-x',
    name: '水平翻转',
    englishName: 'Flip X',
    category: 'basic',
    tags: ['flip', 'basic'],
    description: '元素绕 X 轴翻转入场。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.3, max: 2, step: 0.1, default: 0.8, unit: 's' }
    ],
    code: {
      html: `<div class="flip-x">↻</div>`,
      css: `.flip-x { animation: flipX var(--duration, 0.8s) ease-out both; transform-origin: center; }
@keyframes flipX { from { transform: perspective(600px) rotateX(-90deg); opacity: 0; } to { transform: perspective(600px) rotateX(0); opacity: 1; } }`,
      js: ``,
    },
    preview: lz('flip-x'),
  },
  {
    id: 'rotate-in',
    name: '旋转入场',
    englishName: 'Rotate In',
    category: 'basic',
    tags: ['rotate', 'basic'],
    description: '元素从旋转状态回归原位。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.3, max: 2, step: 0.1, default: 0.7, unit: 's' }
    ],
    code: {
      html: `<div class="rotate-in">★</div>`,
      css: `.rotate-in { animation: rotateIn var(--duration, 0.7s) ease-out both; }
@keyframes rotateIn { from { transform: rotate(-180deg) scale(0.3); opacity: 0; } to { transform: rotate(0) scale(1); opacity: 1; } }`,
      js: ``,
    },
    preview: lz('rotate-in'),
  },
  {
    id: 'pulse',
    name: '脉冲',
    englishName: 'Pulse',
    category: 'basic',
    tags: ['pulse', 'basic'],
    description: '元素持续放大缩小,吸引注意。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 0.5, max: 3, step: 0.1, default: 1.5, unit: 's' },
      { kind: 'range', key: 'intensity', label: '强度', min: 0.05, max: 0.4, step: 0.05, default: 0.15 }
    ],
    code: {
      html: `<div class="pulse">●</div>`,
      css: `.pulse { animation: pulse var(--duration, 1.5s) ease-in-out infinite; }
@keyframes pulse { 0%, 100% { transform: scale(1); } 50% { transform: scale(calc(1 + var(--intensity, 0.15))); } }`,
      js: ``,
    },
    preview: lz('pulse'),
  },
  {
    id: 'shake',
    name: '摇晃',
    englishName: 'Shake',
    category: 'basic',
    tags: ['shake', 'basic'],
    description: '元素左右快速摇晃,常用于表单错误提示。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.2, max: 1.5, step: 0.1, default: 0.5, unit: 's' }
    ],
    code: {
      html: `<div class="shake">!</div>`,
      css: `.shake { animation: shake var(--duration, 0.5s); }
@keyframes shake { 0%, 100% { transform: translateX(0); } 25% { transform: translateX(-8px); } 75% { transform: translateX(8px); } }`,
      js: ``,
    },
    preview: lz('shake'),
  },
  {
    id: 'heartbeat',
    name: '心跳',
    englishName: 'Heartbeat',
    category: 'basic',
    tags: ['heartbeat', 'basic'],
    description: '双拍心跳节奏,模拟真实心跳。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 0.5, max: 3, step: 0.1, default: 1.2, unit: 's' }
    ],
    code: {
      html: `<div class="heartbeat">♥</div>`,
      css: `.heartbeat { animation: heartbeat var(--duration, 1.2s) ease-in-out infinite; }
@keyframes heartbeat { 0%, 100% { transform: scale(1); } 14% { transform: scale(1.3); } 28% { transform: scale(1); } 42% { transform: scale(1.3); } 70% { transform: scale(1); } }`,
      js: ``,
    },
    preview: lz('heartbeat'),
  },
  {
    id: 'marquee',
    name: '跑马灯',
    englishName: 'Marquee',
    category: 'basic',
    tags: ['marquee', 'basic'],
    description: '内容从右向左无限滚动。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 5, max: 30, step: 1, default: 12, unit: 's' },
      { kind: 'select', key: 'direction', label: '方向', options: ["left","right"], default: 'left' }
    ],
    code: {
      html: `<div class="marquee"><span>Motion.Lab · 动效实验室 · </span><span>Motion.Lab · 动效实验室 · </span></div>`,
      css: `.marquee { display: flex; gap: 32px; animation: marquee var(--duration, 12s) linear infinite; white-space: nowrap; }
@keyframes marquee { from { transform: translateX(0); } to { transform: translateX(-50%); } }`,
      js: ``,
    },
    preview: lz('marquee'),
  },
  {
    id: 'spinner',
    name: '加载旋转',
    englishName: 'Spinner',
    category: 'basic',
    tags: ['spinner', 'basic'],
    description: '经典加载指示器。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 0.3, max: 2, step: 0.1, default: 0.8, unit: 's' }
    ],
    code: {
      html: `<div class="spinner"></div>`,
      css: `.spinner { width: 32px; height: 32px; border: 3px solid rgba(0,0,0,0.1); border-top-color: var(--accent); border-radius: 50%; animation: spin var(--duration, 0.8s) linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }`,
      js: ``,
    },
    preview: lz('spinner'),
  },
  {
    id: 'typewriter',
    name: '打字机',
    englishName: 'Typewriter',
    category: 'text',
    tags: ['typewriter', 'text'],
    description: '字符逐个出现,模拟键盘输入。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'speed', label: '速度', min: 20, max: 200, step: 10, default: 80, unit: 'ms' }
    ],
    code: {
      html: `<div id="typewriter"></div>`,
      css: `#typewriter { font-family: monospace; border-right: 2px solid currentColor; padding-right: 4px; animation: caret 0.8s step-end infinite; }
@keyframes caret { 50% { border-color: transparent; } }`,
      js: `const el = document.getElementById('typewriter');
const text = 'Hello, Motion.Lab!';
let i = 0;
setInterval(() => { el.textContent = text.slice(0, i++ % (text.length + 1)); }, 80);`,
    },
    preview: lz('typewriter'),
  },
  {
    id: 'wave-text',
    name: '波浪文字',
    englishName: 'Wave Text',
    category: 'text',
    tags: ['wave', 'text'],
    description: '每个字符上下波动形成波浪。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 0.8, max: 3, step: 0.1, default: 1.6, unit: 's' }
    ],
    code: {
      html: `<span class="wave-text">WAVE</span>`,
      css: `.wave-text span { display: inline-block; animation: wave var(--duration, 1.6s) ease-in-out infinite; }
.wave-text span:nth-child(n) { animation-delay: calc(0.1s * n); }
@keyframes wave { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-12px); } }`,
      js: `document.querySelectorAll('.wave-text').forEach(el => el.innerHTML = [...el.textContent].map(c => \`<span>\${c}</span>\`).join(''));`,
    },
    preview: lz('wave-text'),
  },
  {
    id: 'mask-reveal',
    name: '遮罩揭示',
    englishName: 'Mask Reveal',
    category: 'text',
    tags: ['mask', 'text'],
    description: '文字从遮罩下方揭示,常用于 hero 标题。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.4, max: 2.5, step: 0.1, default: 1.2, unit: 's' }
    ],
    code: {
      html: `<h1 class="mask-reveal">MOTION</h1>`,
      css: `.mask-reveal { clip-path: inset(0 0 100% 0); animation: reveal var(--duration, 1.2s) cubic-bezier(0.65, 0, 0.35, 1) forwards; }
@keyframes reveal { to { clip-path: inset(0 0 0 0); } }`,
      js: ``,
    },
    preview: lz('mask-reveal'),
  },
  {
    id: 'split-char',
    name: '字符分裂',
    englishName: 'Split Character',
    category: 'text',
    tags: ['split', 'text'],
    description: '每个字符从上下分开再合拢。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.4, max: 2, step: 0.1, default: 0.8, unit: 's' }
    ],
    code: {
      html: `<h1 class="split-char">SPLIT</h1>`,
      css: `.split-char span { display: inline-block; animation: split var(--duration, 0.8s) ease-out both; }
.split-char span:nth-child(odd) { animation-name: splitTop; }
.split-char span:nth-child(even) { animation-name: splitBot; }
@keyframes splitTop { from { transform: translateY(-100%); } to { transform: translateY(0); } }
@keyframes splitBot { from { transform: translateY(100%); } to { transform: translateY(0); } }`,
      js: `[...document.querySelector('.split-char').textContent].forEach(c => { const s = document.createElement('span'); s.textContent = c; c.replaceWith(s); });`,
    },
    preview: lz('split-char'),
  },
  {
    id: 'gradient-text',
    name: '渐变文字',
    englishName: 'Gradient Text',
    category: 'text',
    tags: ['gradient', 'text'],
    description: '文字使用 HSL 渐变背景 + 循环动画。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 2, max: 10, step: 0.5, default: 4, unit: 's' }
    ],
    code: {
      html: `<h1 class="gradient-text">COLOR</h1>`,
      css: `.gradient-text { background: linear-gradient(90deg, hsl(0 90% 60%), hsl(120 90% 60%), hsl(240 90% 60%)); background-size: 200% auto; -webkit-background-clip: text; background-clip: text; color: transparent; animation: hue var(--duration, 4s) linear infinite; }
@keyframes hue { to { background-position: 200% 0; } }`,
      js: ``,
    },
    preview: lz('gradient-text'),
  },
  {
    id: 'glitch-text',
    name: '故障文字',
    englishName: 'Glitch Text',
    category: 'text',
    tags: ['glitch', 'text'],
    description: 'RGB 分离故障效果,赛博朋克风。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 1, max: 5, step: 0.1, default: 2.5, unit: 's' }
    ],
    code: {
      html: `<h1 class="glitch" data-text="GLITCH">GLITCH</h1>`,
      css: `.glitch { position: relative; }
.glitch::before, .glitch::after { content: attr(data-text); position: absolute; inset: 0; }
.glitch::before { color: cyan; animation: glitchA var(--duration, 2.5s) infinite; }
.glitch::after { color: magenta; animation: glitchB var(--duration, 2.5s) infinite; }
@keyframes glitchA { 0%, 100% { transform: translate(0); } 20% { transform: translate(-2px, 2px); } 40% { transform: translate(2px, -1px); } }
@keyframes glitchB { 0%, 100% { transform: translate(0); } 20% { transform: translate(2px, -1px); } 40% { transform: translate(-1px, 2px); } }`,
      js: ``,
    },
    preview: lz('glitch-text'),
  },
  {
    id: 'scramble',
    name: '乱码解码',
    englishName: 'Scramble',
    category: 'text',
    tags: ['scramble', 'text'],
    description: '文字先以乱码出现,逐渐解码为目标文字。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.5, max: 3, step: 0.1, default: 1.5, unit: 's' }
    ],
    code: {
      html: `<span id="scramble"></span>`,
      css: `#scramble { font-family: monospace; }`,
      js: `const el = document.getElementById('scramble');
const target = 'SCRAMBLE';
const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%';
let frame = 0;
const interval = setInterval(() => {
  el.textContent = target.split('').map((c, i) => i < frame / 3 ? c : chars[Math.floor(Math.random() * chars.length)]).join('');
  if (frame++ > target.length * 3) clearInterval(interval);
}, 50);`,
    },
    preview: lz('scramble'),
  },
  {
    id: 'count-up',
    name: '数字滚动',
    englishName: 'Count Up',
    category: 'text',
    tags: ['count', 'text'],
    description: '数字从 0 滚动到目标值。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'target', label: '目标值', min: 10, max: 9999, step: 1, default: 1234 }
    ],
    code: {
      html: `<span id="count-up">0</span>`,
      css: `#count-up { font-variant-numeric: tabular-nums; font-weight: 900; font-size: 48px; }`,
      js: `const el = document.getElementById('count-up');
const target = 1234;
const duration = 1500;
const start = performance.now();
const tick = (now) => {
  const t = Math.min(1, (now - start) / duration);
  el.textContent = Math.floor(target * (1 - Math.pow(1 - t, 3)));
  if (t < 1) requestAnimationFrame(tick);
};
requestAnimationFrame(tick);`,
    },
    preview: lz('count-up'),
  },
  {
    id: 'stagger-fade',
    name: '错落淡入',
    englishName: 'Stagger Fade',
    category: 'text',
    tags: ['stagger', 'text'],
    description: '多个文字依次淡入,带 stagger 延迟。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '单项时长', min: 0.2, max: 1.5, step: 0.1, default: 0.5, unit: 's' },
      { kind: 'range', key: 'stagger', label: '间隔', min: 0.05, max: 0.5, step: 0.05, default: 0.1, unit: 's' }
    ],
    code: {
      html: `<ul class="stagger"><li>一</li><li>二</li><li>三</li><li>四</li></ul>`,
      css: `.stagger li { opacity: 0; animation: fadeIn var(--duration, 0.5s) ease-out forwards; }
.stagger li:nth-child(1) { animation-delay: 0s; }
.stagger li:nth-child(2) { animation-delay: var(--stagger, 0.1s); }
.stagger li:nth-child(3) { animation-delay: calc(var(--stagger, 0.1s) * 2); }
.stagger li:nth-child(4) { animation-delay: calc(var(--stagger, 0.1s) * 3); }
@keyframes fadeIn { to { opacity: 1; transform: translateY(0); } }`,
      js: ``,
    },
    preview: lz('stagger-fade'),
  },
  {
    id: 'vertical-marquee',
    name: '垂直跑马灯',
    englishName: 'Vertical Marquee',
    category: 'text',
    tags: ['vertical', 'text'],
    description: '文字从下往上垂直滚动。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '周期', min: 5, max: 30, step: 1, default: 15, unit: 's' }
    ],
    code: {
      html: `<div class="vmarquee"><div>设计 · 设计 · 设计 · 设计</div><div>设计 · 设计 · 设计 · 设计</div></div>`,
      css: `.vmarquee { height: 60px; overflow: hidden; }
.vmarquee > div { animation: vm var(--duration, 15s) linear infinite; }
@keyframes vm { from { transform: translateY(0); } to { transform: translateY(-100%); } }`,
      js: ``,
    },
    preview: lz('vertical-marquee'),
  },
  {
    id: 'magnetic-cursor',
    name: '磁吸光标',
    englishName: 'Magnetic Cursor',
    category: 'interaction',
    tags: ['magnetic', 'interaction'],
    description: '光标靠近元素时元素被吸引。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'strength', label: '强度', min: 0.1, max: 0.8, step: 0.05, default: 0.4 }
    ],
    code: {
      html: `<button class="magnetic">Hover me</button>`,
      css: `.magnetic { transition: transform 0.3s cubic-bezier(0.2, 0.8, 0.2, 1); }`,
      js: `const btn = document.querySelector('.magnetic');
btn.addEventListener('mousemove', (e) => {
  const r = btn.getBoundingClientRect();
  const x = (e.clientX - r.left - r.width / 2) * 0.4;
  const y = (e.clientY - r.top - r.height / 2) * 0.4;
  btn.style.transform = \`translate(\${x}px, \${y}px)\`;
});
btn.addEventListener('mouseleave', () => btn.style.transform = '');`,
    },
    preview: lz('magnetic-cursor'),
  },
  {
    id: 'three-d-tilt',
    name: '3D 倾斜',
    englishName: '3D Tilt',
    category: 'interaction',
    tags: ['3d', 'interaction'],
    description: '卡片随鼠标 3D 倾斜。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'max', label: '最大角度', min: 5, max: 30, step: 1, default: 15, unit: '°' }
    ],
    code: {
      html: `<div class="tilt">TILT</div>`,
      css: `.tilt { transform-style: preserve-3d; transition: transform 0.2s; }`,
      js: `const el = document.querySelector('.tilt');
el.addEventListener('mousemove', (e) => {
  const r = el.getBoundingClientRect();
  const x = (e.clientX - r.left) / r.width - 0.5;
  const y = (e.clientY - r.top) / r.height - 0.5;
  el.style.transform = \`perspective(600px) rotateY(\${x * 30}deg) rotateX(\${-y * 30}deg)\`;
});`,
    },
    preview: lz('three-d-tilt'),
  },
  {
    id: 'ripple-click',
    name: '点击波纹',
    englishName: 'Ripple Click',
    category: 'interaction',
    tags: ['ripple', 'interaction'],
    description: 'Material Design 风格的点击波纹。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.4, max: 1.5, step: 0.1, default: 0.6, unit: 's' }
    ],
    code: {
      html: `<button class="ripple-btn">Click</button>`,
      css: `.ripple-btn { position: relative; overflow: hidden; }
.ripple-btn .ripple { position: absolute; border-radius: 50%; background: rgba(255,255,255,0.5); animation: ripple var(--duration, 0.6s); }
@keyframes ripple { to { transform: scale(4); opacity: 0; } }`,
      js: `document.querySelector('.ripple-btn').addEventListener('click', (e) => {
  const r = e.currentTarget.getBoundingClientRect();
  const ripple = document.createElement('span');
  ripple.className = 'ripple';
  ripple.style.left = (e.clientX - r.left) + 'px';
  ripple.style.top = (e.clientY - r.top) + 'px';
  ripple.style.width = ripple.style.height = '20px';
  e.currentTarget.appendChild(ripple);
  setTimeout(() => ripple.remove(), 600);
});`,
    },
    preview: lz('ripple-click'),
  },
  {
    id: 'parallax-mouse',
    name: '鼠标视差',
    englishName: 'Parallax Mouse',
    category: 'interaction',
    tags: ['parallax', 'interaction'],
    description: '多层元素按不同深度响应鼠标。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'intensity', label: '强度', min: 5, max: 40, step: 1, default: 20, unit: 'px' }
    ],
    code: {
      html: `<div class="parallax"><div class="layer bg" data-depth="1"></div><div class="layer fg" data-depth="3"></div></div>`,
      css: `.parallax { position: relative; }
.layer { position: absolute; inset: 0; transition: transform 0.2s; }`,
      js: `document.querySelector('.parallax').addEventListener('mousemove', (e) => {
  const r = e.currentTarget.getBoundingClientRect();
  const x = (e.clientX - r.left) / r.width - 0.5;
  const y = (e.clientY - r.top) / r.height - 0.5;
  e.currentTarget.querySelectorAll('.layer').forEach(l => {
    const d = +l.dataset.depth;
    l.style.transform = \`translate(\${x * d * 20}px, \${y * d * 20}px)\`;
  });
});`,
    },
    preview: lz('parallax-mouse'),
  },
  {
    id: 'blob-cursor',
    name: '粘性光标',
    englishName: 'Blob Cursor',
    category: 'interaction',
    tags: ['blob', 'interaction'],
    description: '光标变成一个跟随的彩色 blob。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'size', label: '尺寸', min: 20, max: 80, step: 4, default: 40, unit: 'px' }
    ],
    code: {
      html: `<div class="blob"></div>`,
      css: `.blob { position: fixed; width: 40px; height: 40px; border-radius: 50%; background: hsl(280 90% 60%); mix-blend-mode: difference; pointer-events: none; transition: transform 0.15s; }`,
      js: `const blob = document.querySelector('.blob');
document.addEventListener('mousemove', (e) => {
  blob.style.transform = \`translate(\${e.clientX - 20}px, \${e.clientY - 20}px)\`;
});`,
    },
    preview: lz('blob-cursor'),
  },
  {
    id: 'hover-image-distort',
    name: '悬停图像畸变',
    englishName: 'Hover Distort',
    category: 'interaction',
    tags: ['hover', 'interaction'],
    description: '悬停时图像被 SVG 滤镜畸变。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'amount', label: '畸变强度', min: 0, max: 0.05, step: 0.005, default: 0.02 }
    ],
    code: {
      html: `<svg width="0" height="0"><filter id="d"><feTurbulence baseFrequency="0.02" numOctaves="2" /><feDisplacementMap in="SourceGraphic" scale="20" /></filter></svg>
<div class="distort">HOVER</div>`,
      css: `.distort { filter: url(#d); transition: filter 0.3s; }`,
      js: ``,
    },
    preview: lz('hover-image-distort'),
  },
  {
    id: 'magnetic-button',
    name: '磁吸按钮',
    englishName: 'Magnetic Button',
    category: 'interaction',
    tags: ['magnetic', 'interaction'],
    description: '按钮周围区域吸引按钮位移。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'radius', label: '吸引半径', min: 30, max: 200, step: 10, default: 80, unit: 'px' }
    ],
    code: {
      html: `<button class="mag-btn">PRESS</button>`,
      css: `.mag-btn { transition: transform 0.3s cubic-bezier(0.2, 0.8, 0.2, 1); }`,
      js: `const btn = document.querySelector('.mag-btn');
document.addEventListener('mousemove', (e) => {
  const r = btn.getBoundingClientRect();
  const dx = e.clientX - (r.left + r.width / 2);
  const dy = e.clientY - (r.top + r.height / 2);
  const dist = Math.hypot(dx, dy);
  if (dist < 80) btn.style.transform = \`translate(\${dx * 0.3}px, \${dy * 0.3}px)\`;
  else btn.style.transform = '';
});`,
    },
    preview: lz('magnetic-button'),
  },
  {
    id: 'sticky-stack',
    name: '堆叠翻页',
    englishName: 'Sticky Stack',
    category: 'interaction',
    tags: ['sticky', 'interaction'],
    description: '滚动时卡片堆叠翻页效果。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'count', label: '卡片数', min: 3, max: 8, step: 1, default: 4 }
    ],
    code: {
      html: `<div class="stack"><div class="card">1</div><div class="card">2</div><div class="card">3</div></div>`,
      css: `.stack .card { position: sticky; top: 80px; padding: 40px; background: white; border-radius: 16px; margin-bottom: 20px; }`,
      js: ``,
    },
    preview: lz('sticky-stack'),
  },
  {
    id: 'drag-scroll',
    name: '拖动滚动',
    englishName: 'Drag Scroll',
    category: 'interaction',
    tags: ['drag', 'interaction'],
    description: '横向拖动滚动容器。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'duration', label: '惯性时长', min: 0.2, max: 1.5, step: 0.1, default: 0.6, unit: 's' }
    ],
    code: {
      html: `<div class="drag"><div class="drag-inner"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span></div></div>`,
      css: `.drag { overflow: hidden; cursor: grab; user-select: none; }
.drag:active { cursor: grabbing; }
.drag-inner { display: flex; gap: 20px; padding: 20px; }`,
      js: `const wrap = document.querySelector('.drag');
let isDown = false, startX = 0, scrollLeft = 0;
wrap.addEventListener('mousedown', (e) => { isDown = true; startX = e.pageX; scrollLeft = wrap.scrollLeft; });
window.addEventListener('mouseup', () => isDown = false);
wrap.addEventListener('mousemove', (e) => { if (!isDown) return; e.preventDefault(); wrap.scrollLeft = scrollLeft - (e.pageX - startX); });`,
    },
    preview: lz('drag-scroll'),
  },
  {
    id: 'color-picker-hover',
    name: '随悬停变色',
    englishName: 'Color Hover',
    category: 'interaction',
    tags: ['color', 'interaction'],
    description: '悬停位置产生彩色光晕。',
    difficulty: 1,
    params: [
      { kind: 'range', key: 'size', label: '光晕大小', min: 100, max: 600, step: 20, default: 300, unit: 'px' }
    ],
    code: {
      html: `<div class="color-hover"></div>`,
      css: `.color-hover { background: radial-gradient(circle at var(--x, 50%) var(--y, 50%), hsl(var(--h, 0) 90% 60%), transparent 50%); }`,
      js: `const el = document.querySelector('.color-hover');
el.addEventListener('mousemove', (e) => {
  const r = el.getBoundingClientRect();
  el.style.setProperty('--x', (e.clientX - r.left) + 'px');
  el.style.setProperty('--y', (e.clientY - r.top) + 'px');
  el.style.setProperty('--h', Math.random() * 360);
});`,
    },
    preview: lz('color-picker-hover'),
  },
  {
    id: 'gsap-scrollTrigger',
    name: '滚动驱动',
    englishName: 'GSAP ScrollTrigger',
    category: 'advanced',
    tags: ['gsap', 'advanced'],
    description: '使用 GSAP ScrollTrigger 绑定滚动进度。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'distance', label: '位移', min: 50, max: 400, step: 10, default: 200, unit: 'px' }
    ],
    code: {
      html: `<div class="gsap-target">SCROLL</div>`,
      css: `.gsap-target { font-size: 64px; font-weight: 900; }`,
      js: `gsap.registerPlugin(ScrollTrigger);
gsap.to('.gsap-target', { x: 200, scrollTrigger: { trigger: '.gsap-target', start: 'top center', end: 'bottom center', scrub: true } });`,
    },
    preview: lz('gsap-scrollTrigger'),
  },
  {
    id: 'three-particles',
    name: '粒子系统',
    englishName: 'Three.js Particles',
    category: 'advanced',
    tags: ['three.js', 'advanced'],
    description: 'Three.js 渲染的几何粒子系统。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'count', label: '粒子数', min: 100, max: 5000, step: 100, default: 1500 }
    ],
    code: {
      html: `<canvas class="three"></canvas>`,
      css: `.three { width: 100%; height: 100%; }`,
      js: `import * as THREE from 'three';
const scene = new THREE.Scene();
const geom = new THREE.BufferGeometry();
const positions = new Float32Array(1500 * 3);
for (let i = 0; i < 1500 * 3; i++) positions[i] = (Math.random() - 0.5) * 10;
geom.setAttribute('position', new THREE.BufferAttribute(positions, 3));
const mat = new THREE.PointsMaterial({ color: 0xff00ff, size: 0.05 });
scene.add(new THREE.Points(geom, mat));`,
    },
    preview: lz('three-particles'),
  },
  {
    id: 'webgl-shader',
    name: '着色器',
    englishName: 'WebGL Shader',
    category: 'advanced',
    tags: ['webgl', 'advanced'],
    description: '自定义 GLSL 片元着色器生成动画。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'speed', label: '速度', min: 0.1, max: 3, step: 0.1, default: 1 }
    ],
    code: {
      html: `<canvas class="shader"></canvas>`,
      css: `.shader { width: 100%; height: 100%; }`,
      js: `const frag = \`precision mediump float; uniform float u_time; uniform vec2 u_resolution; void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; gl_FragColor = vec4(uv, 0.5 + 0.5 * sin(u_time), 1.0); }\`;`,
    },
    preview: lz('webgl-shader'),
  },
  {
    id: 'canvas-confetti',
    name: '五彩纸屑',
    englishName: 'Canvas Confetti',
    category: 'advanced',
    tags: ['canvas', 'advanced'],
    description: '撒花庆祝效果。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'count', label: '粒子数', min: 30, max: 300, step: 10, default: 120 }
    ],
    code: {
      html: `<canvas class="cv"></canvas>`,
      css: `.cv { position: absolute; inset: 0; pointer-events: none; }`,
      js: `const cv = document.querySelector('.cv'); const ctx = cv.getContext('2d');
const particles = [];
for (let i = 0; i < 120; i++) particles.push({ x: 200, y: 200, vx: (Math.random()-0.5)*8, vy: Math.random()*-12, g: 0.3, c: \`hsl(\${Math.random()*360} 90% 60%)\` });
function tick() { ctx.clearRect(0,0,cv.width,cv.height); particles.forEach(p => { p.vy += p.g; p.x += p.vx; p.y += p.vy; ctx.fillStyle = p.c; ctx.fillRect(p.x, p.y, 6, 6); }); requestAnimationFrame(tick); } tick();`,
    },
    preview: lz('canvas-confetti'),
  },
  {
    id: 'lottie-loader',
    name: 'Lottie 加载',
    englishName: 'Lottie Loader',
    category: 'advanced',
    tags: ['lottie', 'advanced'],
    description: '使用 Lottie 动画作为加载器。',
    difficulty: 2,
    params: [
      { kind: 'select', key: 'style', label: '风格', options: ["pulse","orbit","wave"], default: 'pulse' }
    ],
    code: {
      html: `<div class="lottie"></div>`,
      css: `.lottie { width: 200px; height: 200px; }`,
      js: `import lottie from 'lottie-web';
lottie.loadAnimation({ container: document.querySelector('.lottie'), renderer: 'svg', loop: true, autoplay: true, path: '/animation.json' });`,
    },
    preview: lz('lottie-loader'),
  },
  {
    id: 'morph-svg',
    name: 'SVG 形变',
    englishName: 'Morph SVG',
    category: 'advanced',
    tags: ['morph', 'advanced'],
    description: 'SVG path 之间平滑形变。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'duration', label: '时长', min: 0.4, max: 3, step: 0.1, default: 1.5, unit: 's' }
    ],
    code: {
      html: `<svg viewBox="0 0 100 100"><path class="p" d="M10 50 Q50 10 90 50 Q50 90 10 50" fill="none" stroke="currentColor" stroke-width="4"/></svg>`,
      css: `svg { width: 200px; height: 200px; }`,
      js: `const p = document.querySelector('.p');
const paths = ['M10 50 Q50 10 90 50 Q50 90 10 50', 'M10 10 L90 10 L90 90 L10 90 Z'];
let i = 0; setInterval(() => { p.setAttribute('d', paths[i++ % 2]); }, 1500);`,
    },
    preview: lz('morph-svg'),
  },
  {
    id: 'grid-magnetic',
    name: '网格磁吸',
    englishName: 'Grid Magnetic',
    category: 'advanced',
    tags: ['grid', 'advanced'],
    description: '网格中每个点对鼠标有磁吸反应。',
    difficulty: 3,
    params: [
      { kind: 'range', key: 'radius', label: '吸引半径', min: 40, max: 200, step: 10, default: 100, unit: 'px' }
    ],
    code: {
      html: `<div class="grid-mag"></div>`,
      css: `.grid-mag { position: relative; width: 100%; height: 100%; }
.grid-mag .dot { position: absolute; width: 4px; height: 4px; background: currentColor; border-radius: 50%; transition: transform 0.2s; }`,
      js: `const el = document.querySelector('.grid-mag');
const dots = [];
for (let r = 0; r < 6; r++) for (let c = 0; c < 12; c++) { const d = document.createElement('div'); d.className = 'dot'; d.style.left = c * 24 + 'px'; d.style.top = r * 24 + 'px'; el.appendChild(d); dots.push(d); }
el.addEventListener('mousemove', (e) => { dots.forEach(d => { const r = d.getBoundingClientRect(); const dx = e.clientX - (r.left + 2); const dy = e.clientY - (r.top + 2); const dist = Math.hypot(dx, dy); if (dist < 100) d.style.transform = \`translate(\${dx * 0.3}px, \${dy * 0.3}px)\`; else d.style.transform = ''; }); });`,
    },
    preview: lz('grid-magnetic'),
  },
  {
    id: 'sine-wave',
    name: '正弦波',
    englishName: 'Sine Wave',
    category: 'advanced',
    tags: ['sine', 'advanced'],
    description: 'Canvas 渲染的正弦波。',
    difficulty: 2,
    params: [
      { kind: 'range', key: 'frequency', label: '频率', min: 0.005, max: 0.05, step: 0.005, default: 0.02 },
      { kind: 'range', key: 'amplitude', label: '振幅', min: 10, max: 80, step: 5, default: 30, unit: 'px' }
    ],
    code: {
      html: `<canvas class="wave"></canvas>`,
      css: `.wave { width: 100%; height: 100%; }`,
      js: `const c = document.querySelector('.wave'); const ctx = c.getContext('2d');
let t = 0;
function draw() { ctx.clearRect(0, 0, c.width, c.height); ctx.beginPath();
for (let x = 0; x < c.width; x++) ctx.lineTo(x, c.height/2 + Math.sin(x * 0.02 + t) * 30);
ctx.stroke(); t += 0.05; requestAnimationFrame(draw); } draw();`,
    },
    preview: lz('sine-wave'),
  },
];
